import * as Auto from './Automorphism'
import * as C from './complex'
import * as Comp from './Computation'
import * as H from './quaternion'
import * as Inf from './infix'
import * as Int from './integer'
import * as Iso from './Iso'
import * as De from './Decomposition'
import * as M from './Matrix'
import * as N from './number'
import * as Poly from './Polynomial'
import * as Q from './rational'
import * as TC from './typeclasses'
import * as V from './Vector'

export { Auto, C, Comp, H, Inf, Int, Iso, De, M, N, Poly, Q, TC, V }
